<?php if($block->getData('widgettitle')): ?>
            <h2 class='cloudways-title'><?php echo $block->getData('widgettitle'); ?></h2>
<?php endif; ?>
<?php if($block->getData('widgetcontent')): ?>
            <h2 class='cloudways-content'><?php echo $block->getData('widgetcontent'); ?></h2>
<?php endif; ?>

<!--FOUR BUTTON BLOCK-->
<div class="row nomargin">
<div class="min-height-content content-green-dark col-md-12 col-sm-12 col-xs-12 paddingright paddingbottom box-content valign-parent" style="background-color: black; color: white; padding: 10px;">
<div class="hcaption" style="color: white;" data-target="#box-1">
<div class="pad-bottom-lg green-title" style="padding: 8%;">
<h2 class="banner_title"><?php echo $block->getData('headline1'); ?><?php echo $block->getData('headline1'); ?><?php endif; ?>
</h2>
<h4 class="banner_description"><?php echo $block->getData('subhead'); ?><?php echo $block->getData('subhead'); ?><?php endif; ?></h4>
<a class="cta_button" style="<?php echo $block->getData('textcolor'); ?>color: <?php echo $block->getData('textcolor'); ?>;<?php endif; ?> <?php echo $block->getData('buttonbackground'); ?>background-color: <?php echo $block->getData('buttonbackground'); ?>;<?php endif; ?>" href="<?php echo $block->getData('link1'); ?><?php echo $block->getData('link1'); ?><?php endif; ?>"><?php echo $block->getData('button1'); ?><?php echo $block->getData('button1'); ?><?php endif; ?></a>
<a class="cta_button" style="<?php echo $block->getData('textcolor'); ?>color: <?php echo $block->getData('textcolor'); ?>;<?php endif; ?> <?php echo $block->getData('buttonbackground'); ?>background-color: <?php echo $block->getData('buttonbackground'); ?>;<?php endif; ?>" href="<?php echo $block->getData('link2'); ?><?php echo $block->getData('link2'); ?><?php endif; ?>"><?php echo $block->getData('button2'); ?><?php echo $block->getData('button2'); ?><?php endif; ?></a>
<a class="cta_button" style="<?php echo $block->getData('textcolor'); ?>color: <?php echo $block->getData('textcolor'); ?>;<?php endif; ?> <?php echo $block->getData('buttonbackground'); ?>background-color: <?php echo $block->getData('buttonbackground'); ?>;<?php endif; ?>" href="<?php echo $block->getData('link3'); ?><?php echo $block->getData('link3'); ?><?php endif; ?>"><?php echo $block->getData('button3'); ?><?php echo $block->getData('button3'); ?><?php endif; ?></a>
<a class="cta_button" style="<?php echo $block->getData('textcolor'); ?>color: <?php echo $block->getData('textcolor'); ?>;<?php endif; ?> <?php echo $block->getData('buttonbackground'); ?>background-color: <?php echo $block->getData('buttonbackground'); ?>;<?php endif; ?>" href="<?php echo $block->getData('link4'); ?><?php echo $block->getData('link4'); ?><?php endif; ?>"><?php echo $block->getData('button4'); ?><?php echo $block->getData('button4'); ?><?php endif; ?></a>
</div>
</div>
</div>
<!--END FOUR BUTTON BLOCK-->
